name: event_ticket_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

  

dependencies:
  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.7.0
  dartx: ^1.2.0
  dio: ^5.7.0
  drop_down_list: ^2.0.0
  dropdown_button2: ^2.3.9
  envied: ^1.3.1
  extended_image: ^10.0.1
  firebase_analytics: ^12.0.3
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  firebase_performance_dio: ^0.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_confetti: ^0.5.1
  flutter_hooks: ^0.21.2
  flutter_i18n: ^0.37.0
  flutter_local_notifications: ^19.5.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  form_validator: ^2.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.0.0
  go_router: ^16.3.0
  go_router_paths: ^0.2.2
  google_maps_places_autocomplete_widgets: ^1.3.3
  google_places_autocomplete_text_field: ^2.0.3
  image_picker: ^1.1.2
  json_serializable: ^6.8.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  dio_smart_retry: ^7.0.1
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  spider: ^4.2.2
  timeago: ^3.7.0
  another_flushbar: ^1.12.30
  pretty_dio_logger: ^1.4.0
  modal_bottom_sheet: ^3.0.0
  hooks_riverpod: ^3.0.1


dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-BlackItalic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 100
        style: italic

